//
//  main.cpp
//  EulerProblem2
//
//  Created by Brett Hodges on 1/27/15.
//  Copyright (c) 2015 Brett Hodges. All rights reserved.
//

#include <iostream>

int main(int argc, const char * argv[]) {
    /*
     Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
     
     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     
     By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     
     */
    
    long sum=0;
    long count=0;
    long past1=0;
    long past2=0;
    
    while (count<3500000) {
        if (count<2) {
            count++;
        }else
        count=past1+past2;
        past1=past2;
        past2=count;
        
        if (count%2==0) {
            sum+=count;
        }

        std::cout<<count<<"\n";
        
    }
    
    std::cout <<"Sum of even-valued terms is: "<<sum<<"\n";
    return 0;
}
